# Generated by Django 5.2.6 on 2025-09-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_polls_additional_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polls",
            name="additional_field",
        ),
    ]
